name: Publish API Docs (JSON)

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate API docs (JSON)
        run: bunx typedoc --json docs/api.json src/parser.ts

      - name: Get repo and version
        id: meta
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '/' '__')
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Clone docs repo
        run: |
          git clone https://x-access-token:${{ secrets.DOCS_REPO_TOKEN }}@github.com/charter-vtt/docs.git docs-repo

      - name: Copy API docs
        run: |
          mkdir -p docs-repo/api/${{ steps.meta.outputs.repo_name }}/${{ steps.meta.outputs.version }}
          cp docs/api.json docs-repo/api/${{ steps.meta.outputs.repo_name }}/${{ steps.meta.outputs.version }}/

      - name: Commit and push
        run: |
          cd docs-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs(${{ steps.meta.outputs.repo_name }}): add API docs for v${{ steps.meta.outputs.version }}"
          git push
