name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    permissions:
      contents: write           # Publish GitHub releases
      issues: write             # Comment on released issues
      pull-requests: write      # Comment on released pull requests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for GitHub Packages)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build

      - name: Run tests with coverage
        run: bun test --coverage

      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
